### ISSUE TITLE
genome-browser article category

### ISSUE THREAD

**Issue by Aryllen** [Sage-Bionetworks/synapseDocs#685] opened 2020-02-18 00:18 UTC
What category (or categories) should the [genome-browser.md](https://github.com/Sage-Bionetworks/synapseDocs/blob/gh-pages/articles/genome_browser.md) article be in?

**Comment by Dumindaaa** [comment] 2020-02-18 05:13
In what context would I configure the genome browser widget? 
To properly understand where this document would go, I would need to understand what this article is actually about. My assumption is that someone would use this to visualize their Synapse data somehow, but it is not clear how the tool actually works, and how one would use it with regard to Synapse (Can we discuss?)

Right now, this article really doesn't make sense to go within an existing category within the current structure. This is because we don't really seem to have other articles that directly talks about 'using' the data (i.e. for analysis), other than 'Reproducible Research'

So, for now I would suggest putting it within "Reproducible Research".

But I also think we need to consider renaming "Reproducible Research" to something like "Using Data in Synapse " (Since it also covers, workflows, provenance, docker, etc.)
The blurb for "Using Data in Synapse" should be something that covers all the ways to use the data in synapse for external projects, workflows, etc. TBC

**Comment by kdaily** [comment] 2020-02-19 00:58
Fixed by https://github.com/kdaily/synapseDocs/commit/55e124a47ff779ec31e30dc159a44ac2d209ebb4

**Closed as completed by kdaily** 2020-02-19 00:58 UTC
Labels: Information Infrastructure

**Comment by kdaily** [comment] 2020-02-19 00:59
https://github.com/kdaily/synapseDocs/commit/55e124a47ff779ec31e30dc159a44ac2d209ebb4
